# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  grip_joint:
    has_velocity_limits: true
    max_velocity: 3
    has_acceleration_limits: true
    max_acceleration: 1.5
  grip_joint_sub:
    has_velocity_limits: true
    max_velocity: 3
    has_acceleration_limits: true
    max_acceleration: 1.5
  id_1:
    has_velocity_limits: true
    max_velocity: 75
    has_acceleration_limits: true
    max_acceleration: 75
  id_2:
    has_velocity_limits: true
    max_velocity: 75
    has_acceleration_limits: true
    max_acceleration: 75
  id_3:
    has_velocity_limits: true
    max_velocity: 75
    has_acceleration_limits: true
    max_acceleration: 75
  id_4:
    has_velocity_limits: true
    max_velocity: 75
    has_acceleration_limits: true
    max_acceleration: 75
  id_5:
    has_velocity_limits: true
    max_velocity: 75
    has_acceleration_limits: true
    max_acceleration: 75
  id_6:
    has_velocity_limits: true
    max_velocity: 75
    has_acceleration_limits: true
    max_acceleration: 75
  joint8:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 50
